-- ─────────────────────────────────────────────────────────────────────────────
-- V1 : Initial schema
-- Generated from Hibernate entities; executed once by Flyway on first startup.
-- ─────────────────────────────────────────────────────────────────────────────

-- ── Tables ───────────────────────────────────────────────────────────────────

create table users (
    created_at  timestamp(6),
    id          uuid not null,
    email       varchar(255) not null unique,
    first_name  varchar(255) not null,
    last_name   varchar(255) not null,
    password    varchar(255) not null,
    role        varchar(255) not null check (role in ('USER','DOCTOR','MANAGER','ADMIN')),
    status      varchar(255) not null check (status in ('UNVERIFIED','PENDING','ACTIVE','BANNED','DELETED')),
    primary key (id)
);

create table specializations (
    active  boolean not null,
    id      uuid not null,
    code    varchar(60)  not null unique,
    name    varchar(100) not null,
    primary key (id)
);

create table medical_centers (
    created_at  timestamp(6) not null,
    updated_at  timestamp(6) not null,
    id          uuid not null,
    address     varchar(255),
    city        varchar(255),
    description TEXT,
    email       varchar(255),
    logo_url    varchar(255),
    name        varchar(255) not null,
    phone       varchar(255),
    status      varchar(255) not null check (status in ('PENDING_APPROVAL','ACTIVE','SUSPENDED')),
    type        varchar(255) not null check (type in ('CLINIC','HOSPITAL','PRIVATE_PRACTICE','DIAGNOSTIC_CENTER','REHABILITATION_CENTER')),
    website     varchar(255),
    primary key (id)
);

create table doctor_profiles (
    average_rating  double precision default 0.0 not null,
    is_public       boolean not null,
    total_reviews   integer default 0 not null,
    created_at      timestamp(6) not null,
    updated_at      timestamp(6) not null,
    id              uuid not null,
    user_id         uuid not null unique,
    bio             TEXT,
    license_number  varchar(255),
    photo_url       varchar(255),
    public_id       varchar(255) not null unique,
    primary key (id)
);

create table doctor_profile_specializations (
    doctor_profile_id   uuid not null,
    specialization_id   uuid not null,
    primary key (doctor_profile_id, specialization_id)
);

create table doctor_services (
    active              boolean not null,
    duration_minutes    integer not null,
    price               numeric(10,2),
    doctor_id           uuid not null,
    id                  uuid not null,
    name                varchar(255) not null,
    primary key (id)
);

create table center_memberships (
    invited_at          timestamp(6) not null,
    joined_at           timestamp(6),
    center_id           uuid not null,
    id                  uuid not null,
    invited_by_user_id  uuid,
    user_id             uuid not null,
    role                varchar(255) not null check (role in ('MEMBER','ADMIN')),
    status              varchar(255) not null check (status in ('INVITED','ACTIVE','SUSPENDED','REJECTED')),
    primary key (id),
    unique (user_id, center_id)
);

create table availability_blocks (
    created_at  timestamp(6) not null,
    end_time    timestamp(6) not null,
    start_time  timestamp(6) not null,
    center_id   uuid not null,
    doctor_id   uuid not null,
    id          uuid not null,
    primary key (id)
);

create table appointments (
    created_at      timestamp(6) not null,
    end_time        timestamp(6) not null,
    reserved_until  timestamp(6),
    start_time      timestamp(6) not null,
    block_id        uuid not null,
    id              uuid not null,
    patient_id      uuid not null,
    service_id      uuid not null,
    doctor_notes    TEXT,
    patient_notes   TEXT,
    status          varchar(255) not null check (status in ('SCHEDULED','COMPLETED','CANCELLED','RESERVED','NO_SHOW')),
    primary key (id)
);

create table appointment_reviews (
    is_anonymous    boolean not null,
    rating          integer not null,
    created_at      timestamp(6),
    replied_at      timestamp(6),
    updated_at      timestamp(6),
    appointment_id  uuid not null unique,
    id              uuid not null,
    doctor_reply    TEXT,
    patient_comment TEXT not null,
    primary key (id)
);

create table invite_codes (
    created_at  timestamp(6) not null,
    expires_at  timestamp(6) not null,
    code        varchar(12) not null unique,
    id          uuid not null,
    user_id     uuid not null unique,
    primary key (id)
);

create table password_reset_tokens (
    expiry_date timestamp(6) not null,
    id          bigint generated by default as identity,
    user_id     uuid not null unique,
    token       varchar(255) not null unique,
    primary key (id)
);

create table verification_tokens (
    expiry_date timestamp(6) not null,
    id          bigint generated by default as identity,
    user_id     uuid not null unique,
    token       varchar(255) not null unique,
    primary key (id)
);

-- ── Foreign keys ──────────────────────────────────────────────────────────────

alter table if exists doctor_profiles
    add constraint fk_doctor_profile_user
    foreign key (user_id) references users;

alter table if exists doctor_profile_specializations
    add constraint fk_dps_profile
    foreign key (doctor_profile_id) references doctor_profiles;

alter table if exists doctor_profile_specializations
    add constraint fk_dps_specialization
    foreign key (specialization_id) references specializations;

alter table if exists doctor_services
    add constraint fk_doctor_service_doctor
    foreign key (doctor_id) references users;

alter table if exists center_memberships
    add constraint fk_membership_center
    foreign key (center_id) references medical_centers;

alter table if exists center_memberships
    add constraint fk_membership_user
    foreign key (user_id) references users;

alter table if exists center_memberships
    add constraint fk_membership_invited_by
    foreign key (invited_by_user_id) references users;

alter table if exists availability_blocks
    add constraint fk_block_center
    foreign key (center_id) references medical_centers;

alter table if exists availability_blocks
    add constraint fk_block_doctor
    foreign key (doctor_id) references users;

alter table if exists appointments
    add constraint fk_appointment_block
    foreign key (block_id) references availability_blocks;

alter table if exists appointments
    add constraint fk_appointment_patient
    foreign key (patient_id) references users;

alter table if exists appointments
    add constraint fk_appointment_service
    foreign key (service_id) references doctor_services;

alter table if exists appointment_reviews
    add constraint fk_review_appointment
    foreign key (appointment_id) references appointments;

alter table if exists invite_codes
    add constraint fk_invite_code_user
    foreign key (user_id) references users;

alter table if exists password_reset_tokens
    add constraint fk_password_reset_user
    foreign key (user_id) references users;

alter table if exists verification_tokens
    add constraint fk_verification_token_user
    foreign key (user_id) references users;
