"""
seed/reset.py
=============
Removes seeded demo data in strict dependency order.

Two reset modes
---------------
--reset        (soft reset)
    Deletes only accounts generated by this seed script
    (@clearbook.demo, @example.com, and the three fixed @clearbook.com
    accounts).  Spring Boot's own accounts (admin@, patient@, doctor@
    clearbook.com) and any accounts you created by hand via the UI are
    left untouched.

--full-reset   (hard reset)
    Deletes everything EXCEPT the three accounts Spring Boot creates on
    startup (admin@, patient@, doctor@ clearbook.com) and the
    specializations table (also owned by Spring Boot).
    Use this when you want a completely clean slate, including any
    accounts you registered manually through the UI.

Dependency order (both modes)
------------------------------
appointment_reviews → appointments → availability_blocks →
center_memberships → doctor_profile_specializations →
doctor_services → doctor_profiles → invite_codes / refresh_tokens /
verification_tokens / password_reset_tokens → notifications →
users → medical_centers
"""

# Randomly-generated demo accounts
_DEMO = ["%@clearbook.demo", "%@example.com"]

# Fixed demo accounts (exact match keeps Spring Boot's admin@/patient@/doctor@ safe)
_FIXED = [
    "rmarcjan@clearbook.com",
    "pwrobel@clearbook.com",
    "bkozyra@clearbook.com",
]

# Spring Boot accounts that must NEVER be deleted
_SPRING_BOOT_ACCOUNTS = [
    "admin@clearbook.com",
    "patient@clearbook.com",
    "doctor@clearbook.com",
]


def full_reset_data(cur) -> None:
    """
    Delete ALL user-created data except Spring Boot's own seed accounts
    and the specializations table.  Intended for development use when
    you want a completely clean slate (including manually registered users).
    """
    print("  ⚠  FULL RESET – removing all data except Spring Boot accounts…")

    cur.execute("DELETE FROM appointment_reviews")
    cur.execute("DELETE FROM appointments")
    cur.execute("DELETE FROM availability_blocks")
    cur.execute("DELETE FROM center_memberships")
    cur.execute(
        """
        DELETE FROM doctor_profile_specializations
        WHERE doctor_profile_id IN (
            SELECT dp.id FROM doctor_profiles dp
            JOIN users u ON u.id = dp.user_id
            WHERE u.email != ALL(%s)
        )
        """,
        (_SPRING_BOOT_ACCOUNTS,),
    )
    cur.execute(
        "DELETE FROM doctor_services WHERE doctor_id IN "
        "(SELECT id FROM users WHERE email != ALL(%s))",
        (_SPRING_BOOT_ACCOUNTS,),
    )
    cur.execute(
        "DELETE FROM doctor_profiles WHERE user_id IN "
        "(SELECT id FROM users WHERE email != ALL(%s))",
        (_SPRING_BOOT_ACCOUNTS,),
    )
    for table in ("invite_codes", "refresh_tokens",
                  "verification_tokens", "password_reset_tokens"):
        cur.execute(
            f"DELETE FROM {table} WHERE user_id IN "
            "(SELECT id FROM users WHERE email != ALL(%s))",
            (_SPRING_BOOT_ACCOUNTS,),
        )
    cur.execute(
        "SELECT 1 FROM information_schema.tables WHERE table_name='notifications'"
    )
    if cur.fetchone():
        cur.execute(
            "DELETE FROM notifications WHERE user_id IN "
            "(SELECT id FROM users WHERE email != ALL(%s))",
            (_SPRING_BOOT_ACCOUNTS,),
        )
    cur.execute(
        "DELETE FROM users WHERE email != ALL(%s)",
        (_SPRING_BOOT_ACCOUNTS,),
    )
    cur.execute("DELETE FROM medical_centers")
    print("  ✓ Full reset complete")


def reset_seeded_data(cur) -> None:
    """Delete only demo-seeded accounts (@clearbook.demo, @example.com, fixed accounts)."""
    print("  ⚠  Resetting seeded data…")

    # ── 1. Reviews (owns all rows) ────────────────────────────────────────────
    cur.execute("DELETE FROM appointment_reviews")

    # ── 2. Appointments (owns all rows) ───────────────────────────────────────
    cur.execute("DELETE FROM appointments")

    # ── 3. Availability blocks (owns all rows) ────────────────────────────────
    cur.execute("DELETE FROM availability_blocks")

    # ── 4. Clinic memberships (owns all rows) ─────────────────────────────────
    cur.execute("DELETE FROM center_memberships")

    # ── 5. Doctor–specialization links ───────────────────────────────────────
    cur.execute(
        """
        DELETE FROM doctor_profile_specializations
        WHERE doctor_profile_id IN (
            SELECT dp.id
            FROM   doctor_profiles dp
            JOIN   users u ON u.id = dp.user_id
            WHERE  u.email LIKE %s OR u.email LIKE %s
               OR  u.email = ANY(%s)
        )
        """,
        (*_DEMO, _FIXED),
    )

    # ── 6. Doctor services ────────────────────────────────────────────────────
    cur.execute(
        "DELETE FROM doctor_services WHERE doctor_id IN "
        "(SELECT id FROM users WHERE email LIKE %s OR email LIKE %s OR email = ANY(%s))",
        (*_DEMO, _FIXED),
    )

    # ── 7. Doctor profiles ────────────────────────────────────────────────────
    cur.execute(
        "DELETE FROM doctor_profiles WHERE user_id IN "
        "(SELECT id FROM users WHERE email LIKE %s OR email LIKE %s OR email = ANY(%s))",
        (*_DEMO, _FIXED),
    )

    # ── 8. Token & code tables (no CASCADE in schema – must delete before users)
    for table in ("invite_codes", "refresh_tokens",
                  "verification_tokens", "password_reset_tokens"):
        cur.execute(
            f"DELETE FROM {table} WHERE user_id IN "
            "(SELECT id FROM users WHERE email LIKE %s OR email LIKE %s OR email = ANY(%s))",
            (*_DEMO, _FIXED),
        )

    # ── 9. Notifications (optional table – skip if absent) ────────────────────
    cur.execute(
        "SELECT 1 FROM information_schema.tables WHERE table_name = 'notifications'"
    )
    if cur.fetchone():
        cur.execute(
            "DELETE FROM notifications WHERE user_id IN "
            "(SELECT id FROM users WHERE email LIKE %s OR email LIKE %s OR email = ANY(%s))",
            (*_DEMO, _FIXED),
        )

    # ── 10. Demo user accounts ────────────────────────────────────────────────
    cur.execute(
        "DELETE FROM users WHERE email LIKE %s OR email LIKE %s OR email = ANY(%s)",
        (*_DEMO, _FIXED),
    )

    # ── 11. Medical centres (owns all rows – Spring Boot creates none) ─────────
    cur.execute("DELETE FROM medical_centers")

    print("  ✓ Reset complete")
