package com.clearbook.api.model;

public enum Specialization {
    CARDIOLOGY,
    NEUROLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    DERMATOLOGY,
    GYNECOLOGY,
    PSYCHIATRY,
    OPHTHALMOLOGY,
    RADIOLOGY,
    ONCOLOGY,
    EMERGENCY_MEDICINE,
    INTERNAL_MEDICINE,
    SURGERY,
    UROLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    PULMONOLOGY,
    RHEUMATOLOGY,
    NEPHROLOGY,
    HEMATOLOGY,
    ANESTHESIOLOGY,
    FAMILY_MEDICINE
}
